import type { IReviews } from "./StudentReviews.type";

export const StudentReviewsDummyData: IReviews[] = [
    {
        id: 1,
        name: "Ava Baker",
        image: '/assets/img/svo-student/grades/1.png',
        occupation: "Sales Specialist",
        review: "Ava Baker is an exceptional sales specialist who possesses a wealth of knowledge and experience in the field of sales. I had the pleasure of working with Ava on a project for my business, and I must say that I was thoroughly impressed with her work. From start to finish, Ava demonstrated a high level of professionalism, expertise, and commitment to delivering outstanding results.\n\nOne of the things that stood out to me about Ava was her ability to understand our business needs and tailor her approach to meet them. She took the time to listen to our concerns, assess our strengths and weaknesses, and develop a customized sales strategy that aligned with our goals. Her keen insights and attention to detail helped us to identify new opportunities for growth and increase our revenue.\n\nIn addition to her strategic thinking and analytical skills, Ava is an excellent communicator who knows how to build rapport with clients and prospects. She has a warm and engaging personality that makes it easy to work with her, and she is always willing to lend a listening ear and offer support when needed.\n\nWhat I appreciate most about Ava is her dedication to continuous improvement. She is constantly seeking new ways to refine her skills and stay up-to-date with the latest trends and best practices in sales. This commitment to learning and development has enabled her to become a true expert in her field and deliver exceptional value to her clients.\n\nOverall, I highly recommend Ava Baker as a sales specialist. She is a talented and experienced professional who is committed to helping her clients achieve their goals. If you're looking for someone who can deliver results, provide valuable insights, and build strong relationships, Ava is the perfect choice."
    },
    {
        id: 2,
        name: "",
        image: '/assets/img/svo-student/grades/1.png',
        occupation: "Sales Specialist",
        review: "Ava Baker is an exceptional sales specialist who possesses a wealth of knowledge and experience in the field of sales. I had the pleasure of working with Ava on a project for my business, and I must say that I was thoroughly impressed with her work. From start to finish, Ava demonstrated a high level of professionalism, expertise, and commitment to delivering outstanding results.\n\nOne of the things that stood out to me about Ava was her ability to understand our business needs and tailor her approach to meet them. She took the time to listen to our concerns, assess our strengths and weaknesses, and develop a customized sales strategy that aligned with our goals. Her keen insights and attention to detail helped us to identify new opportunities for growth and increase our revenue.\n\nIn addition to her strategic thinking and analytical skills, Ava is an excellent communicator who knows how to build rapport with clients and prospects. She has a warm and engaging personality that makes it easy to work with her, and she is always willing to lend a listening ear and offer support when needed.\n\nWhat I appreciate most about Ava is her dedication to continuous improvement. She is constantly seeking new ways to refine her skills and stay up-to-date with the latest trends and best practices in sales. This commitment to learning and development has enabled her to become a true expert in her field and deliver exceptional value to her clients.\n\nOverall, I highly recommend Ava Baker as a sales specialist. She is a talented and experienced professional who is committed to helping her clients achieve their goals. If you're looking for someone who can deliver results, provide valuable insights, and build strong relationships, Ava is the perfect choice."
    },
]