import type { Courses } from "./CourseDashboard.type";

export const popularCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'Sales Fundamentals ',
      image: '/assets/img/student-course/popular/popular-course-01.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 99.99,
      rating: 4.1,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'HR Management Basics',
      image: '/assets/img/student-course/popular/popular-course-02.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 99.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'Digital Marketing Strategy',
      image: '/assets/img/student-course/popular/popular-course-03.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'Entrepreneur Fundamentals',
    image: '/assets/img/student-course/popular/popular-course-04.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'Customer Service Essentials',
    image: '/assets/img/student-course/popular/popular-course-05.jfif',
    lecturerName: 'Lily Martinez',
    lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const freeCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'Excel for Business',
      image: '/assets/img/student-course/free/free-course-01.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'Leadership and Influence',
      image: '/assets/img/student-course/free/free-course-02.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'Critical Thinking Skills',
      image: '/assets/img/student-course/free/free-course-03.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'Web Development Basics',
    image: '/assets/img/student-course/free/free-course-04.jfif',
    lecturerName: 'Lily Martinez',
    lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'Graphic Design Essentials',
    image: '/assets/img/student-course/free/free-course-05.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const shortCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'Business Writing',
      image: '/assets/img/student-course/short/short-course-01.png',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'Time Management Skills',
      image: '/assets/img/student-course/short/short-course-02.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'Project Management Basics',
      image: '/assets/img/student-course/short/short-course-03.jfif',
      lecturerName: 'Ryan Ramirez',
      lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'Public Speaking',
    image: '/assets/img/student-course/short/short-course-04.jfif',
    lecturerName: 'Ava Baker',
    lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'Social Media Marketing',
    image: '/assets/img/student-course/short/short-course-05.png',
    lecturerName: 'Liam Mitchell',
    lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const longCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'Data Science Fundamentals',
      image: '/assets/img/student-course/long/long-course-01.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'Photoshop Basics',
      image: '/assets/img/student-course/long/long-course-02.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'Creative Writing',
      image: '/assets/img/student-course/long/long-course-03.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'Financial Accounting',
    image: '/assets/img/student-course/long/long-course-04.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'Marketing Essentials',
    image: '/assets/img/student-course/long/long-course-05.jfif',
    lecturerName: 'Liam Mitchell',
    lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]