import type { Courses } from "./CourseDashboard.type";

export const popularCourseDummyData: Courses[] = [
  { 
      id: 1,
      progress: 0,
      name: 'Sales Fundamentals ',
      image: '/assets/img/student-course/popular/popular-course-01.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 99.99,
      rating: 4.1,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 2,
      progress: 0,
      name: 'HR Management Basics',
      image: '/assets/img/student-course/popular/popular-course-02.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 99.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 3,
      progress: 0,
      name: 'Digital Marketing Strategy',
      image: '/assets/img/student-course/popular/popular-course-03.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    progress: 0,
    name: 'Entrepreneur Fundamentals',
    image: '/assets/img/student-course/popular/popular-course-04.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    progress: 0,
    name: 'Customer Service Essentials',
    image: '/assets/img/student-course/popular/popular-course-05.jfif',
    lecturerName: 'Lily Martinez',
    lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  }
]

export const freeCourseDummyData: Courses[] = [
  { 
      id: 1,
      progress: 0,
      name: 'Excel for Business',
      image: '/assets/img/student-course/free/free-course-01.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 2,
      progress: 0,
      name: 'Leadership and Influence',
      image: '/assets/img/student-course/free/free-course-02.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 200.00,
      lecturers: 10,
      totalHour: 30,
      level: 'Beginner',
  },
  { 
      id: 3,
      progress: 0,
      name: 'Critical Thinking Skills',
      image: '/assets/img/student-course/free/free-course-03.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    progress: 0,
    name: 'Web Development Basics',
    image: '/assets/img/student-course/free/free-course-04.jfif',
    lecturerName: 'Lily Martinez',
    lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    progress: 0,
    name: 'Graphic Design Essentials',
    image: '/assets/img/student-course/free/free-course-05.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const shortCourseDummyData: Courses[] = [
  { 
      id: 1,
      progress: 0,
      name: 'Business Writing',
      image: '/assets/img/student-course/short/short-course-01.png',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      progress: 0,
      name: 'Time Management Skills',
      image: '/assets/img/student-course/short/short-course-02.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      progress: 0,
      name: 'Project Management Basics',
      image: '/assets/img/student-course/short/short-course-03.jfif',
      lecturerName: 'Ryan Ramirez',
      lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    progress: 0,
    name: 'Public Speaking',
    image: '/assets/img/student-course/short/short-course-04.jfif',
    lecturerName: 'Ava Baker',
    lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    progress: 0,
    name: 'Social Media Marketing',
    image: '/assets/img/student-course/short/short-course-05.png',
    lecturerName: 'Liam Mitchell',
    lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const longCourseDummyData: Courses[] = [
  { 
      id: 1,
      progress: 0,
      name: 'Data Science Fundamentals',
      image: '/assets/img/student-course/long/long-course-01.png',
      lecturerName: 'Lily Martinez',
      lecturerImage: '/assets/img/dummy-instructor/lily-martinez.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      progress: 0,
      name: 'Photoshop Basics',
      image: '/assets/img/student-course/long/long-course-02.jfif',
      lecturerName: 'Liam Mitchell',
      lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      progress: 0,
      name: 'Creative Writing',
      image: '/assets/img/student-course/long/long-course-03.jfif',
      lecturerName: 'Ava Baker',
      lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    progress: 0,
    name: 'Financial Accounting',
    image: '/assets/img/student-course/long/long-course-04.jfif',
    lecturerName: 'Ryan Ramirez',
    lecturerImage: '/assets/img/dummy-instructor/ryan-ramirez.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    progress: 0,
    name: 'Marketing Essentials',
    image: '/assets/img/student-course/long/long-course-05.jfif',
    lecturerName: 'Liam Mitchell',
    lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const inProgressCourseDummyData: Courses[] = [
  
  {
    id: 1,
    progress: 90,
    name: 'UI UX Design',
    image: '/assets/img/course/ui-ux-design.png',
    lecturerName: 'David Burn',
    lecturerImage: '/assets/img/dummy-instructor/david-burn.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 2,
    progress: 90,
    name: 'Artificial Intelligence',
    image: '/assets/img/student-course/in-progress/student-ai.jfif',
    lecturerName: 'Nathan Ortiz',
    lecturerImage: '/assets/img/dummy-instructor/nathan-ortiz.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 3,
    progress: 90,
    name: 'Networking',
    image: '/assets/img/student-course/in-progress/network.jfif',
    lecturerName: 'Gabriel Hayes',
    lecturerImage: '/assets/img/dummy-instructor/gabriel-hayes.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 4,
    progress: 90,
    name: 'Marketing',
    image: '/assets/img/student-course/in-progress/marketting.jfif',
    lecturerName: 'Liam Mitchell',
    lecturerImage: '/assets/img/dummy-instructor/liam-mitchell.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 5,
    progress: 90,
    name: 'Accounting',
    image: '/assets/img/student-course/in-progress/accounting.jfif',
    lecturerName: 'Ava Baker',
    lecturerImage: '/assets/img/dummy-instructor/ava-barker.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const completedCourseDummyData: Courses[] = [
  
  {
    id: 1,
    progress: 90,
    name: 'UI UX Design',
    image: '/assets/img/student-course/completed/business-management.jfif',
    lecturerName: 'Tyler Turner',
    lecturerImage: '/assets/img/dummy-instructor/tyler-turner.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 2,
    progress: 90,
    name: 'Artificial Intelligence',
    image: '/assets/img/student-course/completed/business-law.jfif',
    lecturerName: 'Fiona Green',
    lecturerImage: '/assets/img/dummy-instructor/fiona-green.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 3,
    progress: 90,
    name: 'Networking',
    image: '/assets/img/student-course/completed/public-relation.jfif',
    lecturerName: 'Nathan Ortiz',
    lecturerImage: '/assets/img/dummy-instructor/nathan-ortiz.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 4,
    progress: 90,
    name: 'Marketing',
    image: '/assets/img/student-course/completed/media-and-communication.jfif',
    lecturerName: 'Henry Johnson',
    lecturerImage: '/assets/img/dummy-instructor/henry-johnson.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  {
    id: 5,
    progress: 90,
    name: 'Accounting',
    image: '/assets/img/student-course/completed/marketting-strategy.jfif',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]