import type { Courses } from "./CourseDashboard.type";

export const popularCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 6,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]

export const freeCourseDummyData: Courses[] = [
  { 
      id: 1,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 2,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
      id: 3,
      name: 'AI Intelligence',
      image: '/assets/img/course/ai-inteligence.png',
      lecturerName: 'Liam Martin',
      lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
      price: 100.00,
      rating: 4.3,
      review: 10000,
      totalCompleted: 1301290,
      priceWas: 100.00,
      lecturers: 13,
      totalHour: 22,
      level: 'Beginner',
  },
  { 
    id: 4,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 5,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
  { 
    id: 6,
    name: 'AI Intelligence',
    image: '/assets/img/course/ai-inteligence.png',
    lecturerName: 'Liam Martin',
    lecturerImage: '/assets/img/dummy-instructor/liam-martin.jpeg',
    price: 100.00,
    rating: 4.3,
    review: 10000,
    totalCompleted: 1301290,
    priceWas: 100.00,
    lecturers: 13,
    totalHour: 22,
    level: 'Beginner',
  },
]